spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:autotest;MODE=MYSQL;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*.xml
server:
  port: 18080
logging:
  level:
    com.example.autotest: INFO
